#!/bin/bash
killall tmux

export TURTLEBOT_ARM1=pincher
TMUX_SESSION=Nathan_calib
TOP=/home/talos/ros/Nathan

cd ${TOP}
tmux new-session -s "$TMUX_SESSION" -n ${TMUX_SESSION} -d

launch_my_window()
{
    NAME=$1
    COMMAND=$2
    tmux new-window -n "$NAME" "${COMMAND}" 
    sleep 1
}

launch_my_window  "rocore"      "roscore"
launch_my_window  "arm"         "roslaunch turtlebot_arm_bringup arm.launch "
launch_my_window  "kinect"      "roslaunch freenect_launch freenect.launch"
launch_my_window  "calibrate"   "roslaunch turtlebot_arm_kinect_calibration calibrate.launch"

tmux select-window -t "$TMUX_SESSION:2"
tmux attach-session