#!/bin/bash
killall tmux

export TURTLEBOT_ARM1=pincher
TMUX_SESSION=Nathan1
TOP=/home/talos/ros/Nathan
#TOP=$(roscd && cd .. && pwd)


tmux new-session -s "$TMUX_SESSION" -n $(pwd) -d

launch_my_window()
{
    WINDOW=$1
    NAME=$2
    COMMAND=$3
    tmux new-window -t "$TMUX_SESSION:$WINDOW" -n "$NAME" 
    tmux send -t "cd ${TOP}" ENTER
    tmux send -t "$TMUX_SESSION:$WINDOW" "${COMMAND}" ENTER
    sleep 1
}

launch_my_window 1 "rocore" "roscore"
launch_my_window 2 "arm.launch" "roslaunch turtlebot_arm_bringup arm.launch simulation:=true"
launch_my_window 3 "arbotix" "rosrun arbotix_python arbotix_gui"
launch_my_window 4 "moveit"  "roslaunch turtlebot_arm_moveit_config turtlebot_arm_moveit.launch"

#...

# Select window #1 and attach to the WINDOW
tmux select-window -t "$TMUX_SESSION:2"
tmux -2 attach-session -t "$TMUX_SESSION"
