#!/bin/bash
killall tmux

export TURTLEBOT_ARM1=pincher
TMUX_SESSION=Nathan_simulation
TOP=/home/talos/ros/Nathan

cd ${TOP}
tmux new-session -s "$TMUX_SESSION" -n ${TMUX_SESSION} -d

launch_my_window()
{
    NAME=$1
    COMMAND=$2
    tmux new-window -n "$NAME" "${COMMAND}" 
    sleep 1
}

launch_my_window  "rocore"     "roscore"
launch_my_window  "arm.launch" "roslaunch turtlebot_arm_bringup arm_sim.launch "
launch_my_window  "arm.launch" "roslaunch turtlebot_arm_bringup arm_rviz.launch "
launch_my_window  "arbotix"    "rosrun arbotix_python arbotix_gui"
